### ISSUE TITLE
Error after updating to the version 0.3

### ISSUE THREAD

**Issue by sammkj** [apollostack/apollo-server#149]
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sammkj/code/apps/em/server/node_modules/apollo-server/dist/integrations/hapiApollo.js:10:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

EDIT: reverting back to v 0.2.8 works fine

**Comment by helfer** [comment]
It seems that `boom` was added to devDependencies instead of dependencies by mistake. Would you mind making a quick PR?

@nnance @DxCx do any of you know how we could test things like that? Unfortunately this is not the first time we were missing a dependency in a release.
